### ISSUE TITLE
Hosted txtpic

### ISSUE THREAD

**Issue by anowell** [jdormit/txtpic#1]
Hey, cool project. I saw your crate and thought I'd quickly hack together a hosted version for fun.
[![Algorithmia](https://algorithmia.com/algorithms/anowell/txtpic/badge)](https://algorithmia.com/algorithms/anowell/txtpic)

Not much else to see here, just thought I'd point to a fun use of your crate, so feel free to close. (And if you happen to want to maintain/own it on our platform, just let me know.)

**Comment by jdormit** [comment]
Very cool! Thanks for the heads up :)
