### ISSUE TITLE
--width has no effect

### ISSUE THREAD

**Issue by flosse** [jdormit/txtpic#2]
**edit**: it's a bit weird, with some <strike>PNG</strike> files it works as expected with some other it just ignores the `width` argument :-\

**Comment by jdormit** [comment]
It's not very well documented! Theoretically, it tries to find the closest width to what you want that preserves the aspect ratio of the source image. This means that `--width 100` and `--width 105`, for example, will actually come out with the same width image. For certain images, there may be only 1 or 2 viable widths so the option won't appear to do anything.

Of course, it may also be broken for the images you are talking about. Would you mind linking to an image for which it doesn't work for you?

I'll update the docs and the usage text to document the option more clearly.

**Comment by jdormit** [comment]
Docs for `--width` updated in f9ee8d08c68eb28026c841a95388b72ddc82c94d

**Comment by jdormit** [comment]
@flosse I'm closing this issue for now, but feel free to comment here if you find an image for which this is broken.
